arm_controller:
  type: effort_controllers/JointTrajectoryController #effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint:
      p: 1200
      d: 20
      i: 50
      i_clamp: 1
    shoulder_lift_joint:
      p: 800
      d: 50
      i: 200
      i_clamp: 1
    elbow_joint:
      p: 600
      d: 50
      i: 200
      i_clamp: 1
    wrist_1_joint:
      p: 20
      d: 3
      i: 5
      i_clamp: 1
    wrist_2_joint:
      p: 20
      d: 3
      i: 5
      i_clamp: 1
    wrist_3_joint:
      p: 5
      d: 0
      i: 0.5
      i_clamp: 1