arm_controller:
  type: effort_controllers/JointTrajectoryController #effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint:
      p: 1200
      d: 20
      i: 50
      i_clamp: 1
    shoulder_lift_joint:
      p: 900
      d: 50
      i: 200
      i_clamp: 1
    elbow_joint:
      p: 700
      d: 50
      i: 200
      i_clamp: 1
    wrist_1_joint:
      p: 30
      d: 3
      i: 8
      i_clamp: 1
    wrist_2_joint:
      p: 10
      d: 2
      i: 3
      i_clamp: 1
    wrist_3_joint:
      p: 0.1
      d: 0.05
      i: 0
      i_clamp: 1