sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /voxel_grid/output
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: filtered_cloud
    self_mask:
        min_sensor_dist: .1
        self_see_default_padding: .01
        self_see_default_scale: 1.0
        self_see_links:
          - name: base_link
            padding: 0.05
          - name: shoulder_link
            padding: 0.05
          - name: upper_arm_link
            padding: 0.05
          - name: forearm_link
            padding: 0.05
          - name: wrist_1_link
            padding: 0.05
          - name: wrist_2_link
            padding: 0.05
          - name: wrist_3_link
            padding: 0.05
          - name: ee_link
            padding: 0.05
            

